### ISSUE TITLE
~~送大家 Kerbal Space Program 游戏~~

### ISSUE THREAD

**Issue by emptymalei** [InterImm/service#15]
有人要玩的话告诉我，正式版要出了可能要涨价。

在北京时间周六之前告诉我啊。告知我你的 steam 帐号。我只有 steam 帐号可以买。

@unionx @ProtossProbe @styra

**Comment by ProtossProbe** [comment]
30刀实在是太贵了……而且感觉不会怎么常玩_(:з」∠)_

**Comment by emptymalei** [comment]
@ProtossProbe 价格什么的就不用管了啊你们。

**Comment by ProtossProbe** [comment]
游戏还是先别买了。
可以先加个steam好友，方便玩耍。puluobi@gmail.com

**Comment by emptymalei** [comment]
@ProtossProbe  并不知道怎么加好友…… 

http://steamcommunity.com/profiles/76561198108267142

**Comment by emptymalei** [comment]
我想到一个主意，跟果壳 KSP 小组联合搞个 KSP 挑战赛，奖品送 KSP 周边。要求他们把我们的旗子插到某个地方。

**Comment by ProtossProbe** [comment]
可以啊，不过这是官方立flag的节奏么？

**Comment by unionx** [comment]
等我先找找我的 stream 账号啦

**Comment by emptymalei** [comment]
好想买这个：https://www.shapeways.com/product/NWB35WK4A/mars-valles-marineris?li=search-results-1&optionId=40479026

![image](https://cloud.githubusercontent.com/assets/663798/7432174/0308822c-efe3-11e4-9c26-c3e92ba5f1eb.png)

**Comment by emptymalei** [comment]
@unionx 帝老师你晚了……那是上周六之前跟我说……

不过，你加我 steam 吧，我不知道怎么加好友。我送你。

**Comment by unionx** [comment]
那我先加你好友...游戏我去看看，你先别送啦
