### ISSUE TITLE
子域名

### ISSUE THREAD

**Issue by emptymalei** [InterImm/service#21]
我们的 InterImmBook 用的是大写，导致我们的网页链接里面如果 InterImmBook 不是大写会跳到 404，这个问题好久了的，一直不知道怎么解决。

突然发现 GitHub Pages 支持字域名，所以我把 InterImmBook 绑定到一个字域名 `book.interimm.org` 了，这样域名更好记，再也不需要输入大写了，当然原来的域名也是都没有变化的，都可以用。

**Comment by ProtossProbe** [comment]
昨天刚刚发现这个新域名。确实好记多了。

**Comment by emptymalei** [comment]
发现一个奇怪的现象：

![image](https://cloud.githubusercontent.com/assets/663798/10115722/7ba06fcc-63d0-11e5-8cfc-a740f062acad.png)

![image](https://cloud.githubusercontent.com/assets/663798/10115724/8b2b8292-63d0-11e5-941f-554efcfbe155.png)

**Comment by ProtossProbe** [comment]
...可能是服务器那边的avatar还没更新过来吧....

**Comment by emptymalei** [comment]
可能吧。

**Comment by unionx** [comment]
+1 确实好记多了！
