### ISSUE TITLE
知乎专栏开篇

### ISSUE THREAD

**Issue by emptymalei** [InterImm/service#22]
我写了一个初稿，来看看需要改么？

图片在专栏里面有，这里没有复制过来。
这里面的 @ 也不太一样，在专栏里是 @ 的知乎帐号。

@unionx @styra 你们两个要加入这个专栏么？

-----

@星移君 在知乎已经有段时日了，在知乎回答的两个问题也给星移君带来了 800 个赞，200个感谢。在这样一个整数赞整数感谢的时刻，@星移君觉得有必要在知乎有一片属于自己的天地。

作为回（guang）顾（gao），下面是@星移君过去的回答。

* 小行星有利用价值吗？ - 星移君的回答
* 以后的火星旅游有哪些景点值得一去？ - 星移君的回答

与这个话题相关的，还有@章鱼喵的两个回答：

* 殖民巨型气态行星的卫星与殖民火星等行星相比，有什么优劣？ - 章鱼喵的回答
* 火星和地球之间光速有数百至上千秒延迟，未来人类在火星如何部署网站、应用？ - 章鱼喵的回答

而 @ProtossProbe的相关回答就更多了：

* 火星上的风暴是怎么回事？ - ProtossProbe 的回答
* 火星和月球哪个更适合成为人类第一个外星永久殖民地？ - ProtossProbe 的回答
* 如果人类在一颗没有大气，或者大气稀薄的星体上建立殖民地，大量小型陨石是否会对殖民地构成威胁？ - ProtossProbe 的回答

通过这些回答，诸位读者可以感受一下我们这个专栏的定位：

* 我们要聊火箭，聊飞船；
* 我们要聊火星，聊月球；
* 我们要聊火星殖民，聊泰坦开发；
* 我们要聊小行星开发，聊太空城市；
* 我们要聊星际通信，聊星际娱乐；（来 Dota 联机不，星际也行，不不，我是火星服务器。）
* 我们要聊去火星旅游，聊火星的生活小技巧；
* ……

等等，聊字太多，看得我眼花，我揉一下眼睛。

我们会聊一段未来历史：人类如何去了火星，如何建造了基地，如何开发成了火星城市，如何将火星建造成一个独立的星球；火星的未来如何发展，火星如何维持自己在太阳系的重要地位，火星地球化是如何花费了几代人的心血；那些远离地球的传奇故事，那些远去但是曾经辉煌的时刻。

> 我们去的地方不需要路。
>             ——《回到未来》

*******************************************************************

星际移民中心网站（ interimm.org，inter 是 interplanetary 简写，imm 是 immigration 的简写 ）二维码：

星际移民中心的微博
爱看视（jie）频（cao）的各位，我们也有 Bilibili 帐号 星际移民中心的空间 
*******************************************************************

需要澄清的是 @星移君 不是我的帐号，是星际移民中心的一员。这个专栏是我、@星移君、@ProtossProbe 三人共同的专栏。
*******************************************************************
@ProtossProbe 还有很多航天相关的回答：
* 太空探测器外表面一层金色的东西是什么，有什么作用？ - ProtossProbe 的回答
* 3D打印在航天领域中的应用？ - ProtossProbe 的回答
* 为什么宇航员在外太空，头盔上的玻璃内侧没有雾气？ - ProtossProbe 的回答
* 为什么航天器不持续加速以最快的速度到达其它星球？为什么不在太空建立燃料补给站？ - ProtossProbe 的回答
* 亚轨道飞行需要考虑撞击太空垃圾的风险吗？ - ProtossProbe 的回答

**Comment by ProtossProbe** [comment]
> @星移君 在知乎已经有段时日了，在知乎回答的两个问题也给星移君带来了 800 个赞，200个感谢。在这样一个整数赞整数感谢的时刻，@星移君觉得有必要在知乎有一片属于自己的天地。

这个理由我给满分😂

> 我们会聊一段未来历史：

感觉这里就不要用“聊”了，用“讲述”或者其他的？

而且我的那些琐碎回答就不用再提了，放两个有干货的回答就好😂。比如
3D打印在航天领域中的应用？ - ProtossProbe 的回答

另外可以再放点图上去

**Comment by emptymalei** [comment]
@ProtossProbe 嗯嗯我去改改字。第三个回答有点不是那么好，所以我就没放，不过放上去也无妨。

放什么图好呢？

**Comment by ProtossProbe** [comment]
http://www.erikwernquist.com/wanderers/gallery_mars_elevator.html
这里面的图片是可以署名使用的么？感觉很贴合主题

**Comment by emptymalei** [comment]
@ProtossProbe 确实很适合，我去加上。

**Comment by styra** [comment]
@emptymalei 哇噻，好棒！
先别加我吧，等我写出好答案再说……

**Comment by emptymalei** [comment]
@ProtossProbe 哈哈哈可以用图片：

![screenshot_2015-10-16-08-48-43](https://cloud.githubusercontent.com/assets/663798/10544822/cf0b5920-73e2-11e5-8dea-95a1fcb68a87.png)

**Comment by ProtossProbe** [comment]
那太好了wwww。开篇什么时候发？

关于太空电梯的文章，文字我已经基本写好了，不过公式先空着的..

**Comment by emptymalei** [comment]
@ProtossProbe 等我周末吧，今天还要给talk什么的需要准备一下。

话说其实也就意味着我可以在别的地方用他的图片。

**Comment by emptymalei** [comment]
@styra 不知道你的知乎帐号呢

**Comment by emptymalei** [comment]
@ProtossProbe 
http://www.zhihu.com/question/30392735?rf=28255173
通过这个说明，好像发私信给 http://www.zhihu.com/people/biglau 说明一下
* 专栏写作方向；
* 与写作方向有关的背景说明（文字说明、相关链接等方式均可）。
刘尧 将在 24 小时之内反馈专栏申请。

**Comment by styra** [comment]
@emptymalei 我的知乎帐号是这个：http://www.zhihu.com/people/zhou-zhao-11

**Comment by unionx** [comment]
求加！

PS. 我最近在看我们在星海航纪的文，需要统一一下设定吗？

**Comment by emptymalei** [comment]
@unionx 加了。写什么的话，现在这里讨论一下/发一下草稿比较好。
